networks:
  iternal-lumin:
    name: iternal-lumin
  exposed-lumin:
    name: exposed-lumin
services:
  back:
    image: eclipse-temurin:latest
    volumes:
      - ./jvm/home:/home
    networks:
      - iternal-lumin
      - exposed-lumin
    ports:
      - 8090:8080
    depends_on:
      - postgres
    restart: always
    entrypoint: /bin/bash /home/startup.sh
#    command: /bin/bash
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/home:/home
    networks:
      - exposed-lumin
    depends_on:
      - back
    entrypoint: /bin/bash /home/startup.sh
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus/
      - ./prometheus/home:/home
    networks:
      - iternal-lumin
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - iternal-lumin
    depends_on:
      - prometheus
  postgres:
    build: ./postgres
    restart: always
#    ports:
#      - 5432:5432
    environment:
      POSTGRES_PASSWORD: my-secret-pw
    volumes:
      - ./postgres/home:/home
      - ./postgres/root:/root
      - ./postgres/init.d:/docker-entrypoint-initdb.d
    networks:
      - iternal-lumin
  redis:
    image: redis:alpine
    restart: always
    networks:
      - iternal-lumin